version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: dataset_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  kedro:
    image: kedro_img   # Usar la imagen de Kedro ya construida "kedro_img"
    container_name: kedro_container
    networks:
      - mynetwork
    volumes:
      - ./kedro_project:/home/kedro_docker/kedro_project:delegated  # Monta la carpeta local 'kedro_project'
      - ./docker/entrypoint.sh:/entrypoint.sh  # Monta el script de entrada
    entrypoint: ["/bin/bash", "/entrypoint.sh"]  # Ejecuta el script de entrada
    ports:
      - "8888:8888"  # Si vas a usar kedro viz o algún otro servicio web
    user: "${UID}:${GID}"  # Establece el usuario y grupo del contenedor al mismo que el del host

volumes:
  postgres_data:
  kedro_data:

networks:
  mynetwork:
    driver: bridge
